- name: Prepare building environment & building artifact
  hosts: builder
  become: true 

  tasks:
  - name: Setting up building environment
    apt: 
     name: 
      - openjdk-11-jdk
      - maven
      - git
      - rsync
     state: present
  - name: creating sources directory
    file
     path: /src
     state: directory
  - name: Clone code repository
    git:
     repo: https://github.com/99North/Sample-Web-App.git
     dest: /src
  - name: Build artifacts
    shell:
     chdir: /src
     cmd: mvn package
  - name: Copy artifact to an managing server
    fetch:
      src: /src/target/WebApp.war
      dest: /usr/src/
      
- name: Pushing artifact to a remote application server and preparing environment
  hosts: app_server
  become: true

  tasks:
   - name: Deploy artifact from builder to a remote application server
     copy:
      src: /usr/src/81.26.190.112/src/target/WebApp.war
      dest: /usr/local/tomcat/webapps
   - name: Install rsync and tomcat
     apt:
      name:
       - tomcat9
       - rsync
      state: present
   - name: Start Tomcat daemon
     service:
      name: tomcat
      state: started

