- name: Prepare building environment & building artifact
  hosts: builder
  become: true 

  tasks:
  - name: Setting up building environment
    apt: 
     name: 
      - openjdk-11-jdk
      - maven
      - git
      - rsync
     state: present
  - name: creating sources directory
    file:
     path: /src
     state: directory
  - name: Clone code repository
    git:
     repo: https://github.com/99North/Sample-Web-App.git
     dest: /src
  - name: Build artifacts
    shell:
     chdir: /src
     cmd: mvn package
  - name: Generate ssh key
    user:
     name: root 
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: .ssh/root_key
  - name: Register key withing ansible fact
    slurp:
     src: /root/.ssh/root_key.pub
    register: builder_public_key_b64
  - name: 
    set_fact:
      builder_public_key: "{{ builder_public_key_b64.content | b64decode }}"


  

- name: Preparing remote application server
  hosts: app_server
  become: true

  tasks:
   - name: Install rsync and tomcat
     apt:
      name:
       - tomcat9
       - rsync
      state: present
   - name: Adding a remote auth key
     authorized_key:
      user: root
      state: present
      key: "{{ hostvars[groups['builder'][0]]['builder_public_key'] }}"

- name: Pushing artifact to a remote application server
  hosts: builder
  become: true

  tasks:
   - name: Deploy artifact from builder to a remote application server
     shell:
      chdir: /src/target
      cmd: "scp *.war {{ hostvars['app_server']['ansible_host'] }}:/usr/local/tomcat/webapps"

- name: Starting application server
  hosts: app_server
  become: true

  tasks:
   - name: Start Tomcat daemon
     service:
      name: tomcat
      state: started

