#SPDX-License-Identifier: MIT-0
---
# vars file for building_artifacts
build_image: 'alpine:latest'
run_image:  'tomcat:latest'
app_repo: https://github.com/99North/Sample-Web-App.git
source_folder: ./