#SPDX-License-Identifier: MIT-0
---
# tasks file for separate_build_deploy
- name: Update apt cache
  apt: 
    update_cache: yes

- name: Install CRE packages
  apt:
    name: docker.io
    state: present

